create_cftc_cit_supplement_table_cmd = """
    CREATE TABLE cftc_cit_supplement (
    date DATE NOT NULL,
    Market_and_Exchange_Names TEXT NOT NULL,
    CFTC_Contract_Market_Code TEXT NOT NULL,
    CFTC_Market_Code TEXT NOT NULL,
    CFTC_Region_Code BIGINT NOT NULL,
    CFTC_Commodity_Code BIGINT NOT NULL,
    Open_Interest_All BIGINT NOT NULL,
    NComm_Positions_Long_All_NoCIT BIGINT NOT NULL,
    NComm_Positions_Short_All_NoCIT BIGINT NOT NULL,
    NComm_Postions_Spread_All_NoCIT BIGINT NOT NULL,
    Comm_Positions_Long_All_NoCIT BIGINT NOT NULL,
    Comm_Positions_Short_All_NoCIT BIGINT NOT NULL,
    Tot_Rept_Positions_Long_All BIGINT NOT NULL,
    Tot_Rept_Positions_Short_All BIGINT NOT NULL,
    NonRept_Positions_Long_All BIGINT NOT NULL,
    NonRept_Positions_Short_All BIGINT NOT NULL,
    CIT_Positions_Long_All BIGINT NOT NULL,
    CIT_Positions_Short_All BIGINT NOT NULL,
    Change_Open_Interest_All BIGINT,
    Change_NonComm_Long_All_NoCIT BIGINT,
    Change_NonComm_Short_All_NoCIT BIGINT,
    Change_NonComm_Spread_All_NoCIT BIGINT,
    Change_Comm_Long_All_NoCIT BIGINT,
    Change_Comm_Short_All_NoCIT BIGINT,
    Change_Tot_Rept_Long_All BIGINT,
    Change_Tot_Rept_Short_All BIGINT,
    Change_NonRept_Long_All BIGINT,
    Change_NonRept_Short_All BIGINT,
    Change_CIT_Long_All BIGINT,
    Change_CIT_Short_All BIGINT,
    Pct_Open_Interest_All FLOAT NOT NULL,
    Pct_OI_NonComm_Long_All_NoCIT FLOAT NOT NULL,
    Pct_OI_NonComm_Short_All_NoCIT FLOAT NOT NULL,
    Pct_OI_NonComm_Spread_All_NoCIT FLOAT NOT NULL,
    Pct_OI_Comm_Long_All_NoCIT FLOAT NOT NULL,
    Pct_OI_Comm_Short_All_NoCIT FLOAT NOT NULL,
    Pct_OI_Tot_Rept_Long_All_NoCIT FLOAT NOT NULL,
    Pct_OI_Tot_Rept_Short_All_NoCIT FLOAT NOT NULL,
    Pct_OI_NonRept_Long_All_NoCIT FLOAT NOT NULL,
    Pct_OI_NonRept_Short_All_NoCIT FLOAT NOT NULL,
    Pct_OI_CIT_Long_All FLOAT NOT NULL,
    Pct_OI_CIT_Short_All FLOAT NOT NULL,
    Traders_Tot_All BIGINT NOT NULL,
    Traders_NonComm_Long_All_NoCIT BIGINT NOT NULL,
    Traders_NonComm_Short_All_NoCIT BIGINT NOT NULL,
    Traders_NonComm_Spread_All_NoCIT BIGINT NOT NULL,
    Traders_Comm_Long_All_NoCIT BIGINT NOT NULL,
    Traders_Comm_Short_All_NoCIT BIGINT NOT NULL,
    Traders_Tot_Rept_Long_All_NoCIT BIGINT NOT NULL,
    Traders_Tot_Rept_Short_All_NoCIT BIGINT NOT NULL,
    Traders_CIT_Long_All BIGINT NOT NULL,
    Traders_CIT_Short_All BIGINT NOT NULL,
    Contract_Units TEXT NOT NULL,
    PRIMARY KEY (date, Market_and_Exchange_Names));"""

create_cftc_futures_only_reports_table_cmd = """
    CREATE TABLE cftc_futures_only_reports (
    date DATE NOT NULL,
    Market_and_Exchange_Names TEXT NOT NULL,
    CFTC_Contract_Market_Code TEXT NOT NULL,
    CFTC_Market_Code TEXT NOT NULL,
    CFTC_Region_Code BIGINT NOT NULL,
    CFTC_Commodity_Code BIGINT NOT NULL,
    Open_Interest_All BIGINT NOT NULL,
    NonComm_Positions_Long_All BIGINT NOT NULL,
    NonComm_Positions_Short_All BIGINT NOT NULL,
    NonComm_Postions_Spread_All BIGINT NOT NULL,
    Comm_Positions_Long_All BIGINT NOT NULL,
    Comm_Positions_Short_All BIGINT NOT NULL,
    Tot_Rept_Positions_Long_All BIGINT NOT NULL,
    Tot_Rept_Positions_Short_All BIGINT NOT NULL,
    NonRept_Positions_Long_All BIGINT NOT NULL,
    NonRept_Positions_Short_All BIGINT NOT NULL,
    Open_Interest_Old BIGINT NOT NULL,
    NonComm_Positions_Long_Old BIGINT NOT NULL,
    NonComm_Positions_Short_Old BIGINT NOT NULL,
    NonComm_Positions_Spread_Old BIGINT NOT NULL,
    Comm_Positions_Long_Old BIGINT NOT NULL,
    Comm_Positions_Short_Old BIGINT NOT NULL,
    Tot_Rept_Positions_Long_Old BIGINT NOT NULL,
    Tot_Rept_Positions_Short_Old BIGINT NOT NULL,
    NonRept_Positions_Long_Old BIGINT NOT NULL,
    NonRept_Positions_Short_Old BIGINT NOT NULL,
    Open_Interest_Other BIGINT NOT NULL,
    NonComm_Positions_Long_Other BIGINT NOT NULL,
    NonComm_Positions_Short_Other BIGINT NOT NULL,
    NonComm_Positions_Spread_Other BIGINT NOT NULL,
    Comm_Positions_Long_Other BIGINT NOT NULL,
    Comm_Positions_Short_Other BIGINT NOT NULL,
    Tot_Rept_Positions_Long_Other BIGINT NOT NULL,
    Tot_Rept_Positions_Short_Other BIGINT NOT NULL,
    NonRept_Positions_Long_Other BIGINT NOT NULL,
    NonRept_Positions_Short_Other BIGINT NOT NULL,
    Change_in_Open_Interest_All BIGINT,
    Change_in_NonComm_Long_All BIGINT,
    Change_in_NonComm_Short_All BIGINT,
    Change_in_NonComm_Spread_All BIGINT,
    Change_in_Comm_Long_All BIGINT,
    Change_in_Comm_Short_All BIGINT,
    Change_in_Tot_Rept_Long_All BIGINT,
    Change_in_Tot_Rept_Short_All BIGINT,
    Change_in_NonRept_Long_All BIGINT,
    Change_in_NonRept_Short_All BIGINT,
    Pct_of_Open_Interest_All FLOAT NOT NULL,
    Pct_of_OI_NonComm_Long_All FLOAT NOT NULL,
    Pct_of_OI_NonComm_Short_All FLOAT NOT NULL,
    Pct_of_OI_NonComm_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Comm_Long_All FLOAT NOT NULL,
    Pct_of_OI_Comm_Short_All FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_All FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_All FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_All FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_All FLOAT NOT NULL,
    Pct_of_Open_Interest_Old FLOAT NOT NULL,
    Pct_of_OI_NonComm_Long_Old FLOAT NOT NULL,
    Pct_of_OI_NonComm_Short_Old FLOAT NOT NULL,
    Pct_of_OI_NonComm_Spread_Old FLOAT NOT NULL,
    Pct_of_OI_Comm_Long_Old FLOAT NOT NULL,
    Pct_of_OI_Comm_Short_Old FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_Old FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_Old FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_Old FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_Old FLOAT NOT NULL,
    Pct_of_Open_Interest_Other FLOAT NOT NULL,
    Pct_of_OI_NonComm_Long_Other FLOAT NOT NULL,
    Pct_of_OI_NonComm_Short_Other FLOAT NOT NULL,
    Pct_of_OI_NonComm_Spread_Other FLOAT NOT NULL,
    Pct_of_OI_Comm_Long_Other FLOAT NOT NULL,
    Pct_of_OI_Comm_Short_Other FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_Other FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_Other FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_Other FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_Other FLOAT NOT NULL,
    Traders_Tot_All BIGINT NOT NULL,
    Traders_NonComm_Long_All BIGINT NOT NULL,
    Traders_NonComm_Short_All BIGINT NOT NULL,
    Traders_NonComm_Spread_All BIGINT NOT NULL,
    Traders_Comm_Long_All BIGINT NOT NULL,
    Traders_Comm_Short_All BIGINT NOT NULL,
    Traders_Tot_Rept_Long_All BIGINT NOT NULL,
    Traders_Tot_Rept_Short_All BIGINT NOT NULL,
    Traders_Tot_Old BIGINT NOT NULL,
    Traders_NonComm_Long_Old BIGINT NOT NULL,
    Traders_NonComm_Short_Old BIGINT NOT NULL,
    Traders_NonComm_Spread_Old BIGINT NOT NULL,
    Traders_Comm_Long_Old BIGINT NOT NULL,
    Traders_Comm_Short_Old BIGINT NOT NULL,
    Traders_Tot_Rept_Long_Old BIGINT NOT NULL,
    Traders_Tot_Rept_Short_Old BIGINT NOT NULL,
    Traders_Tot_Other BIGINT NOT NULL,
    Traders_NonComm_Long_Other BIGINT NOT NULL,
    Traders_NonComm_Short_Other BIGINT NOT NULL,
    Traders_NonComm_Spread_Other BIGINT NOT NULL,
    Traders_Comm_Long_Other BIGINT NOT NULL,
    Traders_Comm_Short_Other BIGINT NOT NULL,
    Traders_Tot_Rept_Long_Other BIGINT NOT NULL,
    Traders_Tot_Rept_Short_Other BIGINT NOT NULL,
    Conc_Gross_LE_4_TDR_Long_All FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_All FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_All FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_All FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_All FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_All FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_All FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_All FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Long_Old FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_Old FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_Old FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_Old FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_Old FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_Old FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_Old FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_Old FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Long_Other FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_Other FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_Other FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_Other FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_Other FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_Other FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_Other FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_Other FLOAT NOT NULL,
    Contract_Units TEXT,
    PRIMARY KEY (date, Market_and_Exchange_Names, CFTC_Contract_Market_Code));"""

create_cftc_tff_futures_only_table_cmd = """
    CREATE TABLE cftc_tff_futures_only (
    date DATE NOT NULL,
    Market_and_Exchange_Names TEXT NOT NULL,
    CFTC_Contract_Market_Code TEXT NOT NULL,
    CFTC_Market_Code TEXT NOT NULL,
    CFTC_Region_Code BIGINT NOT NULL,
    CFTC_Commodity_Code BIGINT NOT NULL,
    Open_Interest_All BIGINT NOT NULL,
    Dealer_Positions_Long_All BIGINT NOT NULL,
    Dealer_Positions_Short_All BIGINT NOT NULL,
    Dealer_Positions_Spread_All BIGINT NOT NULL,
    Asset_Mgr_Positions_Long_All BIGINT NOT NULL,
    Asset_Mgr_Positions_Short_All BIGINT NOT NULL,
    Asset_Mgr_Positions_Spread_All BIGINT NOT NULL,
    Lev_Money_Positions_Long_All BIGINT NOT NULL,
    Lev_Money_Positions_Short_All BIGINT NOT NULL,
    Lev_Money_Positions_Spread_All BIGINT NOT NULL,
    Other_Rept_Positions_Long_All BIGINT NOT NULL,
    Other_Rept_Positions_Short_All BIGINT NOT NULL,
    Other_Rept_Positions_Spread_All BIGINT NOT NULL,
    Tot_Rept_Positions_Long_All BIGINT NOT NULL,
    Tot_Rept_Positions_Short_All BIGINT NOT NULL,
    NonRept_Positions_Long_All BIGINT NOT NULL,
    NonRept_Positions_Short_All BIGINT NOT NULL,
    Change_in_Open_Interest_All BIGINT,
    Change_in_Dealer_Long_All BIGINT,
    Change_in_Dealer_Short_All BIGINT,
    Change_in_Dealer_Spread_All BIGINT,
    Change_in_Asset_Mgr_Long_All BIGINT,
    Change_in_Asset_Mgr_Short_All BIGINT,
    Change_in_Asset_Mgr_Spread_All BIGINT,
    Change_in_Lev_Money_Long_All BIGINT,
    Change_in_Lev_Money_Short_All BIGINT,
    Change_in_Lev_Money_Spread_All BIGINT,
    Change_in_Other_Rept_Long_All BIGINT,
    Change_in_Other_Rept_Short_All BIGINT,
    Change_in_Other_Rept_Spread_All BIGINT,
    Change_in_Tot_Rept_Long_All BIGINT,
    Change_in_Tot_Rept_Short_All BIGINT,
    Change_in_NonRept_Long_All BIGINT,
    Change_in_NonRept_Short_All BIGINT,
    Pct_of_Open_Interest_All FLOAT NOT NULL,
    Pct_of_OI_Dealer_Long_All FLOAT NOT NULL,
    Pct_of_OI_Dealer_Short_All FLOAT NOT NULL,
    Pct_of_OI_Dealer_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Asset_Mgr_Long_All FLOAT NOT NULL,
    Pct_of_OI_Asset_Mgr_Short_All FLOAT NOT NULL,
    Pct_of_OI_Asset_Mgr_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Lev_Money_Long_All FLOAT NOT NULL,
    Pct_of_OI_Lev_Money_Short_All FLOAT NOT NULL,
    Pct_of_OI_Lev_Money_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Long_All FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Short_All FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_All FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_All FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_All FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_All FLOAT NOT NULL,
    Traders_Tot_All BIGINT NOT NULL,
    Traders_Dealer_Long_All BIGINT,
    Traders_Dealer_Short_All BIGINT,
    Traders_Dealer_Spread_All BIGINT,
    Traders_Asset_Mgr_Long_All BIGINT,
    Traders_Asset_Mgr_Short_All BIGINT,
    Traders_Asset_Mgr_Spread_All BIGINT,
    Traders_Lev_Money_Long_All BIGINT,
    Traders_Lev_Money_Short_All BIGINT,
    Traders_Lev_Money_Spread_All BIGINT,
    Traders_Other_Rept_Long_All BIGINT,
    Traders_Other_Rept_Short_All BIGINT,
    Traders_Other_Rept_Spread_All BIGINT,
    Traders_Tot_Rept_Long_All BIGINT,
    Traders_Tot_Rept_Short_All BIGINT,
    Conc_Gross_LE_4_TDR_Long_All FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_All FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_All FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_All FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_All FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_All FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_All FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_All FLOAT NOT NULL,
    Contract_Units TEXT NOT NULL,
    CFTC_SubGroup_Code TEXT NOT NULL,
    FutOnly_or_Combined TEXT NOT NULL,
    PRIMARY KEY (date, Market_and_Exchange_Names, CFTC_Contract_Market_Code));"""

create_cftc_disaggregated_futures_only_reports_table_cmd = """
    CREATE TABLE cftc_disaggregated_futures_only_reports (
    date DATE NOT NULL, 
    Market_and_Exchange_Names TEXT NOT NULL,
    CFTC_Contract_Market_Code TEXT NOT NULL,
    CFTC_Market_Code TEXT NOT NULL,
    CFTC_Region_Code BIGINT NOT NULL,
    CFTC_Commodity_Code BIGINT NOT NULL,
    Open_Interest_All BIGINT NOT NULL,
    Prod_Merc_Positions_Long_ALL BIGINT NOT NULL,
    Prod_Merc_Positions_Short_ALL BIGINT NOT NULL,
    Swap_Positions_Long_All BIGINT NOT NULL,
    Swap_Positions_Short_All BIGINT NOT NULL,
    Swap_Positions_Spread_All BIGINT NOT NULL,
    M_Money_Positions_Long_ALL BIGINT NOT NULL,
    M_Money_Positions_Short_ALL BIGINT NOT NULL,
    M_Money_Positions_Spread_ALL BIGINT NOT NULL,
    Other_Rept_Positions_Long_ALL BIGINT NOT NULL,
    Other_Rept_Positions_Short_ALL BIGINT NOT NULL,
    Other_Rept_Positions_Spread_ALL BIGINT NOT NULL,
    Tot_Rept_Positions_Long_All BIGINT NOT NULL,
    Tot_Rept_Positions_Short_All BIGINT NOT NULL,
    NonRept_Positions_Long_All BIGINT NOT NULL,
    NonRept_Positions_Short_All BIGINT NOT NULL,
    Open_Interest_Old BIGINT NOT NULL,
    Prod_Merc_Positions_Long_Old BIGINT NOT NULL,
    Prod_Merc_Positions_Short_Old BIGINT NOT NULL,
    Swap_Positions_Long_Old BIGINT NOT NULL,
    Swap_Positions_Short_Old BIGINT NOT NULL,
    Swap_Positions_Spread_Old BIGINT NOT NULL,
    M_Money_Positions_Long_Old BIGINT NOT NULL,
    M_Money_Positions_Short_Old BIGINT NOT NULL,
    M_Money_Positions_Spread_Old BIGINT NOT NULL,
    Other_Rept_Positions_Long_Old BIGINT NOT NULL,
    Other_Rept_Positions_Short_Old BIGINT NOT NULL,
    Other_Rept_Positions_Spread_Old BIGINT NOT NULL,
    Tot_Rept_Positions_Long_Old BIGINT NOT NULL,
    Tot_Rept_Positions_Short_Old BIGINT NOT NULL,
    NonRept_Positions_Long_Old BIGINT NOT NULL,
    NonRept_Positions_Short_Old BIGINT NOT NULL,
    Open_Interest_Other BIGINT NOT NULL,
    Prod_Merc_Positions_Long_Other BIGINT NOT NULL,
    Prod_Merc_Positions_Short_Other BIGINT NOT NULL,
    Swap_Positions_Long_Other BIGINT NOT NULL,
    Swap_Positions_Short_Other BIGINT NOT NULL,
    Swap_Positions_Spread_Other BIGINT NOT NULL,
    M_Money_Positions_Long_Other BIGINT NOT NULL,
    M_Money_Positions_Short_Other BIGINT NOT NULL,
    M_Money_Positions_Spread_Other BIGINT NOT NULL,
    Other_Rept_Positions_Long_Other BIGINT NOT NULL,
    Other_Rept_Positions_Short_Other BIGINT NOT NULL,
    Other_Rept_Positions_Spread_Othr BIGINT NOT NULL,
    Tot_Rept_Positions_Long_Other BIGINT NOT NULL,
    Tot_Rept_Positions_Short_Other BIGINT NOT NULL,
    NonRept_Positions_Long_Other BIGINT NOT NULL,
    NonRept_Positions_Short_Other BIGINT NOT NULL,
    Change_in_Open_Interest_All BIGINT,
    Change_in_Prod_Merc_Long_All BIGINT,
    Change_in_Prod_Merc_Short_All BIGINT,
    Change_in_Swap_Long_All BIGINT,
    Change_in_Swap_Short_All BIGINT,
    Change_in_Swap_Spread_All BIGINT,
    Change_in_M_Money_Long_All BIGINT,
    Change_in_M_Money_Short_All BIGINT,
    Change_in_M_Money_Spread_All BIGINT,
    Change_in_Other_Rept_Long_All BIGINT,
    Change_in_Other_Rept_Short_All BIGINT,
    Change_in_Other_Rept_Spread_All BIGINT,
    Change_in_Tot_Rept_Long_All BIGINT,
    Change_in_Tot_Rept_Short_All BIGINT,
    Change_in_NonRept_Long_All BIGINT,
    Change_in_NonRept_Short_All BIGINT,
    Pct_of_Open_Interest_All FLOAT NOT NULL,
    Pct_of_OI_Prod_Merc_Long_All FLOAT NOT NULL,
    Pct_of_OI_Prod_Merc_Short_All FLOAT NOT NULL,
    Pct_of_OI_Swap_Long_All FLOAT NOT NULL,
    Pct_of_OI_Swap_Short_All FLOAT NOT NULL,
    Pct_of_OI_Swap_Spread_All FLOAT NOT NULL,
    Pct_of_OI_M_Money_Long_All FLOAT NOT NULL,
    Pct_of_OI_M_Money_Short_All FLOAT NOT NULL,
    Pct_of_OI_M_Money_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Long_All FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Short_All FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Spread_All FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_All FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_All FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_All FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_All FLOAT NOT NULL,
    Pct_of_Open_Interest_Old FLOAT NOT NULL,
    Pct_of_OI_Prod_Merc_Long_Old FLOAT NOT NULL,
    Pct_of_OI_Prod_Merc_Short_Old FLOAT NOT NULL,
    Pct_of_OI_Swap_Long_Old FLOAT NOT NULL,
    Pct_of_OI_Swap_Short_Old FLOAT NOT NULL,
    Pct_of_OI_Swap_Spread_Old FLOAT NOT NULL,
    Pct_of_OI_M_Money_Long_Old FLOAT NOT NULL,
    Pct_of_OI_M_Money_Short_Old FLOAT NOT NULL,
    Pct_of_OI_M_Money_Spread_Old FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Long_Old FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Short_Old FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Spread_Old FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_Old FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_Old FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_Old FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_Old FLOAT NOT NULL,
    Pct_of_Open_Interest_Other FLOAT NOT NULL,
    Pct_of_OI_Prod_Merc_Long_Other FLOAT NOT NULL,
    Pct_of_OI_Prod_Merc_Short_Other FLOAT NOT NULL,
    Pct_of_OI_Swap_Long_Other FLOAT NOT NULL,
    Pct_of_OI_Swap_Short_Other FLOAT NOT NULL,
    Pct_of_OI_Swap_Spread_Other FLOAT NOT NULL,
    Pct_of_OI_M_Money_Long_Other FLOAT NOT NULL,
    Pct_of_OI_M_Money_Short_Other FLOAT NOT NULL,
    Pct_of_OI_M_Money_Spread_Other FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Long_Other FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Short_Other FLOAT NOT NULL,
    Pct_of_OI_Other_Rept_Spread_Othr FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Long_Other FLOAT NOT NULL,
    Pct_of_OI_Tot_Rept_Short_Other FLOAT NOT NULL,
    Pct_of_OI_NonRept_Long_Other FLOAT NOT NULL,
    Pct_of_OI_NonRept_Short_Other FLOAT NOT NULL,
    Traders_Tot_All BIGINT,
    Traders_Prod_Merc_Long_All BIGINT,
    Traders_Prod_Merc_Short_All BIGINT,
    Traders_Swap_Long_All BIGINT,
    Traders_Swap_Short_All BIGINT,
    Traders_Swap_Spread_All BIGINT,
    Traders_M_Money_Long_All BIGINT,
    Traders_M_Money_Short_All BIGINT,
    Traders_M_Money_Spread_All BIGINT,
    Traders_Other_Rept_Long_All BIGINT,
    Traders_Other_Rept_Short_All BIGINT,
    Traders_Other_Rept_Spread_All BIGINT,
    Traders_Tot_Rept_Long_All BIGINT,
    Traders_Tot_Rept_Short_All BIGINT,
    Traders_Tot_Old BIGINT,
    Traders_Prod_Merc_Long_Old BIGINT,
    Traders_Prod_Merc_Short_Old BIGINT,
    Traders_Swap_Long_Old BIGINT,
    Traders_Swap_Short_Old BIGINT,
    Traders_Swap_Spread_Old BIGINT,
    Traders_M_Money_Long_Old BIGINT,
    Traders_M_Money_Short_Old BIGINT,
    Traders_M_Money_Spread_Old BIGINT,
    Traders_Other_Rept_Long_Old BIGINT,
    Traders_Other_Rept_Short_Old BIGINT,
    Traders_Other_Rept_Spread_Old BIGINT,
    Traders_Tot_Rept_Long_Old BIGINT,
    Traders_Tot_Rept_Short_Old BIGINT,
    Traders_Tot_Other BIGINT,
    Traders_Prod_Merc_Long_Other BIGINT,
    Traders_Prod_Merc_Short_Other BIGINT,
    Traders_Swap_Long_Other BIGINT,
    Traders_Swap_Short_Other BIGINT,
    Traders_Swap_Spread_Other BIGINT,
    Traders_M_Money_Long_Other BIGINT,
    Traders_M_Money_Short_Other BIGINT,
    Traders_M_Money_Spread_Other BIGINT,
    Traders_Other_Rept_Long_Other BIGINT,
    Traders_Other_Rept_Short_Other BIGINT,
    Traders_Other_Rept_Spread_Other BIGINT,
    Traders_Tot_Rept_Long_Other BIGINT,
    Traders_Tot_Rept_Short_Other BIGINT,
    Conc_Gross_LE_4_TDR_Long_All FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_All FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_All FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_All FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_All FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_All FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_All FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_All FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Long_Old FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_Old FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_Old FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_Old FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_Old FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_Old FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_Old FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_Old FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Long_Other FLOAT NOT NULL,
    Conc_Gross_LE_4_TDR_Short_Other FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Long_Other FLOAT NOT NULL,
    Conc_Gross_LE_8_TDR_Short_Other FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Long_Other FLOAT NOT NULL,
    Conc_Net_LE_4_TDR_Short_Other FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Long_Other FLOAT NOT NULL,
    Conc_Net_LE_8_TDR_Short_Other FLOAT NOT NULL,
    Contract_Units TEXT NOT NULL,
    CFTC_SubGroup_Code TEXT NOT NULL,
    FutOnly_or_Combined TEXT NOT NULL,
    PRIMARY KEY (date, Market_and_Exchange_Names, CFTC_Contract_Market_Code));"""